[myconnection]
account = "EKJHKPW-IR25446"
user = "CICD_USER"
authenticator = "SNOWFLAKE_JWT"
private_key_file = ".github/workflows/private_key.p8"
private_key_file_pwd = "shashank"
warehouse = "DEVELOPER_WH"